service:
  name: node-ecma-serverless-gql

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs10.x

functions:
  qiita:
    handler: qiita.hello
    environment:
      endpoint: https://qiita.com/api/v2/users/harhogefoo/items

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
